### ISSUE TITLE
Issues with libcronet HTTP1.0

### ISSUE THREAD

**Issue by triggered96** [binarycraft007/libcronet#1]
It seems that libcronet supports HTTP2, but in my actual testing, I found that when I set SetEnableHTTP2 to false, Wireshark detected that libcronet was unable to send requests in HTTP1.0. Do you have any solutions?

https://github.com/binarycraft007/naiveproxy/blob/master/src/components/cronet/native/generated/cronet.idl_impl_struct.cc#L271-L275
```
void Cronet_EngineParams_enable_http2_set(Cronet_EngineParamsPtr self,
                                          const bool enable_http2) {
  DCHECK(self);
  self->enable_http2 = enable_http2;
}
```

**Comment by binarycraft007** [comment]
> It seems that libcronet supports HTTP2, but in my actual testing, I found that when I set SetEnableHTTP2 to false, Wireshark detected that libcronet was unable to send requests in HTTP1.0. Do you have any solutions?
> 
> https://github.com/binarycraft007/naiveproxy/blob/master/src/components/cronet/native/generated/cronet.idl_impl_struct.cc#L271-L275
> 
> ```
> void Cronet_EngineParams_enable_http2_set(Cronet_EngineParamsPtr self,
>                                           const bool enable_http2) {
>   DCHECK(self);
>   self->enable_http2 = enable_http2;
> }
> ```

made an example in zig, http2 is working, but if I turn off http2, it seems that I am getting errors from cronet:

With http2: 
```
❯ zig-out/bin/cronet https://www.google.com
info: on_stream_ready_callback
info: on_response_headers_received, negotiated_protocol=h2
info: :status: 302
info: location: https://www.google.com.hk/url?sa=p&hl=zh-CN&pref=hkredirect&pval=yes&q=https://www.google.com.hk/&ust=1678176669813955&usg=AOvVaw3UKIjLFXVbiVOM6Vwy1yJI
info: cache-control: private
info: content-type: text/html; charset=UTF-8
info: p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
info: date: Tue, 07 Mar 2023 08:10:39 GMT
info: server: gws
info: content-length: 372
info: x-xss-protection: 0
info: x-frame-options: SAMEORIGIN
info: set-cookie: 1P_JAR=2023-03-07-08; expires=Thu, 06-Apr-2023 08:10:39 GMT; path=/; domain=.google.com; Secure
info: set-cookie: AEC=ARSKqsLPDfjc_8hvNqjv8jdQI6FFflKa6EgIDbxEvi0HW3OJT0qbIpUlcg; expires=Sun, 03-Sep-2023 08:10:39 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
info: set-cookie: NID=511=h2Lwe0auofyl8DaKJYpf2n0AisRi55W0b37NMvX-Pr8Sas7XsZDJzVIG-VkWJfD-HWwqmeVroF0rk0mqH6DjkwceSlgp8Azxznc4E9IcAgP1cRtZiSsYvupvMn65LPJJ4ILMA3AsGP2G0Ipk34diWOCPzyc3R70VadqYRj5YQWg; expires=Wed, 06-Sep-2023 08:10:39 GMT; path=/; domain=.google.com; HttpOnly
info: alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
info: on_read_completed
info: <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://www.google.com.hk/url?sa=p&amp;hl=zh-CN&amp;pref=hkredirect&amp;pval=yes&amp;q=https://www.google.com.hk/&amp;ust=1678176669813955&amp;usg=AOvVaw3UKIjLFXVbiVOM6Vwy1yJI">here</A>.
</BODY></HTML>

info: on_read_completed
info: <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://www.google.com.hk/url?sa=p&amp;hl=zh-CN&amp;pref=hkredirect&amp;pval=yes&amp;q=https://www.google.com.hk/&amp;ust=1678176669813955&amp;usg=AOvVaw3UKIjLFXVbiVOM6Vwy1yJI">here</A>.
</BODY></HTML>

info: on_succeded
```

Without http2:
```
❯ zig-out/bin/cronet https://www.google.com                                                                                                                                                                                                    
info: on_failed                                                                                                                                                                                                                                
info: net error: -2
```

**Comment by triggered96** [comment]
Only supporting HTTP2 means no CDN

**Comment by triggered96** [comment]
I see you have a cronet-zig project, unfortunately I can't zig. How to compile?

**Comment by triggered96** [comment]
If I'm going to study it, I have to study zig. After all, my main force is C.

**Comment by triggered96** [comment]
If you want to integrate cronet into zig, you may have to consider http1.0, after all ws. Of course, http2 can also request ws, but cdn is not supported.

**Comment by binarycraft007** [comment]
> I see you have a cronet-zig project, unfortunately I can't zig. How to compile?

download latest release from here https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.1836+28364166e.tar.xz,
add path of zig/lib/zig.exe to $PATH, and run zig build, you will get the executable in zig-out/bin

**Comment by triggered96** [comment]
This may require changing the code of chromium to adapt to the request of http1.0, and then compile the cronet.

**Comment by triggered96** [comment]
> > I see you have a cronet-zig project, unfortunately I can't zig. How to compile?
> 
> download latest release from here https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.1836+28364166e.tar.xz, add path of zig/lib/zig.exe to $PATH, and run zig build, you will get the executable in zig-out/bin

ok let me try

**Comment by binarycraft007** [comment]
> If I'm going to study it, I have to study zig. After all, my main force is C.

zig can actually export c api, and generate c obj

**Comment by triggered96** [comment]
> > If I'm going to study it, I have to study zig. After all, my main force is C.
> 
> zig can actually export c api, and generate c obj

OK, I'll try it.

**Comment by binarycraft007** [comment]
> > > I see you have a cronet-zig project, unfortunately I can't zig. How to compile?
> > 
> > 
> > download latest release from here https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.1836+28364166e.tar.xz, add path of zig/lib/zig.exe to $PATH, and run zig build, you will get the executable in zig-out/bin
> 
> ok let me try

ok, you may also need libcronet.so and its headers

**Comment by triggered96** [comment]
I have quickly built your project and it is running successfully. Same as your result, only http2 is supported, if you need to initiate http1.0, you need to change the code of chromium.

```
root@Ubuntu20:~/cronet-zig# ./zig-out/bin/cronet https://www.google.com    
[0307/163537.198852:ERROR:cert_verify_proc_builtin.cc(603)] No net_fetcher for performing AIA chasing.
info: on_stream_ready_callback
info: on_response_headers_received, negotiated_protocol=h2
info: :status: 200
info: date: Tue, 07 Mar 2023 08:35:37 GMT
info: expires: -1
info: cache-control: private, max-age=0
info: content-type: text/html; charset=ISO-8859-1
info: p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
info: server: gws
info: x-xss-protection: 0
info: x-frame-options: SAMEORIGIN
info: set-cookie: 1P_JAR=2023-03-07-08; expires=Thu, 06-Apr-2023 08:35:37 GMT; path=/; domain=.google.com; Secure
info: set-cookie: AEC=ARSKqsKZgGH-Pnin3gtucCo4jAg45f_zuOGBg1DQDLbEU59Yg9ADrAkAYBM; expires=Sun, 03-Sep-2023 08:35:37 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax

```

**Comment by triggered96** [comment]
> > > > I see you have a cronet-zig project, unfortunately I can't zig. How to compile?
> > > 
> > > 
> > > download latest release from here https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.1836+28364166e.tar.xz, add path of zig/lib/zig.exe to $PATH, and run zig build, you will get the executable in zig-out/bin
> > 
> > 
> > ok let me try
> 
> ok, you may also need libcronet.so and its headers

It may be modified under net/spdy of chromium to support http1.0.

**Comment by binarycraft007** [comment]
> > > > > I see you have a cronet-zig project, unfortunately I can't zig. How to compile?
> > > > 
> > > > 
> > > > download latest release from here https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.1836+28364166e.tar.xz, add path of zig/lib/zig.exe to $PATH, and run zig build, you will get the executable in zig-out/bin
> > > 
> > > 
> > > ok let me try
> > 
> > 
> > ok, you may also need libcronet.so and its headers
> 
> It may be modified under net/spdy of chromium to support http1.0.

I was actually trying to use zig build system to build cronet, modifying chromium code seems too much work

**Comment by triggered96** [comment]
> spdy

Yes, if you use libcronet, that means only http2 or quic. After all, libcronet is built under the spdy package. of course, maybe you just want to reuse chromium's browser fingerprint.

**Comment by binarycraft007** [comment]
> > > > > I see you have a cronet-zig project, unfortunately I can't zig. How to compile?
> > > > 
> > > > 
> > > > download latest release from here https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.1836+28364166e.tar.xz, add path of zig/lib/zig.exe to $PATH, and run zig build, you will get the executable in zig-out/bin
> > > 
> > > 
> > > ok let me try
> > 
> > 
> > ok, you may also need libcronet.so and its headers
> 
> It may be modified under net/spdy of chromium to support http1.0.

there is two direction for a tls fingerprinting resistant proxy, one is use chromium network stack, another is to modify , clienthello message of tls library. I am trying out both

**Comment by triggered96** [comment]
> > > > > > I see you have a cronet-zig project, unfortunately I can't zig. How to compile?
> > > > > 
> > > > > 
> > > > > download latest release from here https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.1836+28364166e.tar.xz, add path of zig/lib/zig.exe to $PATH, and run zig build, you will get the executable in zig-out/bin
> > > > 
> > > > 
> > > > ok let me try
> > > 
> > > 
> > > ok, you may also need libcronet.so and its headers
> > 
> > 
> > It may be modified under net/spdy of chromium to support http1.0.
> 
> there is two direction for a tls fingerprinting resistant proxy, one is use chromium network stack, another is to modify , clienthello message of tls library. I am trying out both

Yes, I think the same as you. utls are nowhere near the true fingerprint of chromium.
